### ISSUE TITLE
Folding Nested Control-Else folds everything

### ISSUE THREAD

**Issue by Arthri** [SpecialEliteSNP/yagpdb-cc-ext#1]
This causes folding to break:
```
{{ if true }}
    {{ if true }} {{/* Fold this */}}
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    {{ else }}
        Nullam in viverra nisi, at commodo orci.
    {{ end }}
    Nullam in viverra nisi, at commodo orci
{{ end }}
```

Before:
![image](https://user-images.githubusercontent.com/41360489/111272022-00ecac80-866d-11eb-81e8-316f3ae191ea.png)

After:
![image](https://user-images.githubusercontent.com/41360489/111272028-034f0680-866d-11eb-9671-4aad51a43034.png)

**Comment by SpecialEliteSNP** [comment]
Just dropped [a new version](https://marketplace.visualstudio.com/items?itemName=SpecialEliteSNP.yagpdb-cc), version [1.1.0](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/SpecialEliteSNP/vsextensions/yagpdb-cc/1.1.0/vspackage) that should fix the folding issue you were having. If not, lmk.

**Comment by Arthri** [comment]
Thank you! It works now
